# Generated by Django 2.2.5 on 2019-12-02 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField(null=True)),
                ('deathday', models.DateField(null=True)),
                ('known_for', models.CharField(max_length=30)),
                ('tmdb_id', models.IntegerField()),
                ('imdb_id', models.CharField(max_length=9)),
                ('name', models.CharField(max_length=50)),
                ('popularity', models.FloatField()),
                ('biography', models.TextField(null=True)),
                ('photo', models.URLField(null=True)),
            ],
            options={
                'db_table': 'people',
                'ordering': ['-popularity'],
            },
        ),
    ]
