# Generated by Django 2.2.5 on 2019-12-02 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0001_initial'),
        ('people', '0003_auto_20191202_0459'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=20)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Person')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='titles.Title')),
            ],
            options={
                'db_table': 'creator_role',
            },
        ),
        migrations.CreateModel(
            name='ActorRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(max_length=100)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Person')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='titles.Title')),
            ],
            options={
                'db_table': 'actor_role',
            },
        ),
        migrations.AddField(
            model_name='person',
            name='acting',
            field=models.ManyToManyField(related_name='cast', through='people.ActorRole', to='titles.Title'),
        ),
        migrations.AddField(
            model_name='person',
            name='works',
            field=models.ManyToManyField(related_name='crew', through='people.CreatorRole', to='titles.Title'),
        ),
    ]
