# Generated by Django 2.2.5 on 2019-12-14 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0003_auto_20191212_1433'),
        ('people', '0005_auto_20191209_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatorrole',
            name='job',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='actorrole',
            unique_together={('title', 'actor', 'character')},
        ),
        migrations.AlterUniqueTogether(
            name='creatorrole',
            unique_together={('title', 'creator', 'job')},
        ),
    ]
