version: '3.7'


#networks:
#  scalenet:
#    driver: bridge
#    ipam:
#      config:
#        - subnet: 10.50.0.0/16


services:
  db:
    image: postgres
    restart: always
    hostname: db
    volumes:
      - /var/lib/postgresql/data
  web:
    build: .
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    links:
      - db
    depends_on:
      - db