# Generated by Django 2.2.5 on 2019-11-12 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0002_auto_20191112_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='recommendations',
            field=models.ManyToManyField(related_name='_titles_recommendations_+', to='titles.Titles'),
        ),
    ]
