# Generated by Django 2.2.5 on 2019-11-12 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0004_auto_20191112_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='popularity',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='titles',
            name='release_date',
            field=models.DateField(null=True),
        ),
    ]
