# Generated by Django 2.2.5 on 2019-11-12 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0006_auto_20191113_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='titles',
            name='tmdb_id',
            field=models.IntegerField(null=True),
        ),
    ]
