# Generated by Django 2.2.5 on 2019-11-12 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0007_titles_tmdb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='titles',
            name='is_movie',
            field=models.BooleanField(default=True),
        ),
    ]
