# Generated by Django 2.2.5 on 2019-11-14 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0009_auto_20191113_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='recommendations',
            field=models.ManyToManyField(db_table='title_recommendation', related_name='_titles_recommendations_+', to='titles.Titles'),
        ),
    ]
