# Generated by Django 2.2.5 on 2019-11-14 23:30

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('titles', '0010_auto_20191115_0221'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genres',
            new_name='Genre',
        ),
    ]
