# Generated by Django 2.2.5 on 2019-11-20 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0016_auto_20191120_1600'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={},
        ),
    ]
