# Generated by Django 2.2.5 on 2019-12-26 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrate',
            old_name='title_id',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='userrate',
            old_name='user_id',
            new_name='user',
        ),
    ]
