# Generated by Django 2.2.5 on 2019-11-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Titles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backdrop_url', models.CharField(max_length=50, null=True)),
                ('poster_url', models.CharField(max_length=50, null=True)),
                ('budget', models.IntegerField(null=True)),
                ('homepage', models.URLField(null=True)),
                ('imdb_id', models.CharField(max_length=9)),
                ('name', models.CharField(max_length=50)),
                ('overview', models.TextField(null=True)),
                ('popularity', models.IntegerField(null=True)),
                ('release_date', models.DateField()),
                ('revenue', models.IntegerField(null=True)),
                ('runtime', models.DurationField(null=True)),
                ('status', models.CharField(max_length=20, null=True)),
                ('vote_average', models.FloatField(null=True)),
                ('vote_count', models.IntegerField(default=0)),
                ('type', models.CharField(max_length=20, null=True)),
                ('episode_runtime', models.DurationField(null=True)),
                ('number_of_episodes', models.IntegerField(default=1)),
                ('number_of_seasons', models.IntegerField(default=1)),
                ('last_air_date', models.DateField(null=True)),
                ('recommendations', models.ManyToManyField(null=True, related_name='_titles_recommendations_+', to='apps.titles.Titles')),
            ],
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('titles', models.ManyToManyField(to='apps.titles.Titles')),
            ],
        ),
    ]
