# Generated by Django 2.2.5 on 2019-12-02 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_movie', models.BooleanField(default=True)),
                ('backdrop_url', models.CharField(max_length=50, null=True)),
                ('poster_url', models.CharField(max_length=50, null=True)),
                ('budget', models.IntegerField(null=True)),
                ('homepage', models.URLField(null=True)),
                ('imdb_id', models.CharField(max_length=9, null=True)),
                ('tmdb_id', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=50)),
                ('overview', models.TextField(null=True)),
                ('popularity', models.FloatField(null=True)),
                ('release_date', models.DateField(null=True)),
                ('revenue', models.IntegerField(null=True)),
                ('runtime', models.IntegerField(null=True)),
                ('status', models.CharField(max_length=20, null=True)),
                ('vote_average', models.FloatField(null=True)),
                ('vote_count', models.IntegerField(default=0)),
                ('type', models.CharField(max_length=20, null=True)),
                ('episode_runtime', models.IntegerField(null=True)),
                ('number_of_episodes', models.IntegerField(default=1)),
                ('number_of_seasons', models.IntegerField(default=1)),
                ('last_air_date', models.DateField(null=True)),
            ],
            options={
                'db_table': 'titles',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_movie_genre', models.BooleanField(default=True)),
                ('is_both_genre', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('titles', models.ManyToManyField(db_table='title_genre', to='titles.Title')),
            ],
            options={
                'db_table': 'genres',
                'ordering': ('name',),
            },
        ),
    ]
