# Generated by Django 2.2.5 on 2019-12-12 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0002_image'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='image',
            table='titles_images',
        ),
    ]
