# Generated by Django 2.2.5 on 2019-11-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('titles', '0003_auto_20191112_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genres',
            name='titles',
            field=models.ManyToManyField(db_table='title_genre', to='apps.titles.Titles'),
        ),
        migrations.AlterModelTable(
            name='genres',
            table='genres',
        ),
        migrations.AlterModelTable(
            name='titles',
            table='titles',
        ),
    ]
