# Generated by Django 2.2.5 on 2019-12-23 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0005_auto_20191223_2335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ('-popularity',)},
        ),
    ]
