# Generated by Django 2.2.5 on 2019-11-12 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0005_auto_20191113_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='episode_runtime',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='titles',
            name='runtime',
            field=models.IntegerField(null=True),
        ),
    ]
