# Generated by Django 2.2.5 on 2019-12-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0006_auto_20191224_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='is_both_genre',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='genre',
            name='is_movie_genre',
            field=models.BooleanField(default=0),
        ),
    ]
