# Generated by Django 2.2.5 on 2019-12-26 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0007_auto_20191225_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='is_both_genre',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='is_movie_genre',
        ),
    ]
