# Generated by Django 2.2.5 on 2019-11-12 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0008_titles_is_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='imdb_id',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
