# Generated by Django 2.2.5 on 2019-11-20 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0015_genre_is_both_genre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ('name',)},
        ),
    ]
